#!/bin/zsh
# zsh
alias ezsh="nvim ~/.config/.my-zsh/.zshrc"
alias ealias="nvim ~/.config/.my-zsh/aliases"
alias szsh="source ~/.config/.my-zsh/.zshrc"

# git
alias gs='git status'
alias ga='git add'
alias gp='git push'
alias gpo='git push origin'
alias gtd='git tag --delete'
alias gtdr='git tag --delete origin'
alias gr='git branch -r'
alias gplo='git pull origin'
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias gco='git checkout '
alias gl='git log'
alias gr='git remote'
alias grs='git remote show'
alias glo='git log --pretty="oneline"'
alias glol='git log --graph --oneline --decorate'
function gcp() {
  git add .
  git commit -m "$1"
  git push
}

# basic 
alias ls='ls --color=auto'
alias lsl='ls -l'
alias ll='ls -lahF'
alias lls='ls -lahFtr'
alias la='ls -A'
alias l='ls -CF'
alias lah='ls -alh'
alias cp='cp -avr'
alias mv='mv -v'
alias rm='rm -fr'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# development
# vim
alias vim='nvim'
alias vi='nvim'
alias svim='sudoedit'
alias dvim="vim -u /usr/share/nvim/archlinux.vim" # nvim with default config
alias nvimc='rm -I $VIMCONFIG/swap/*'             # clean nvim swap file
alias nvimcu='rm -I $VIMCONFIG/undo/*'            # clean the vim undo

# go
alias gosrc="$GOPATH/src/" # golang src
alias gobin="$GOPATH/bin/" # golang bin
alias gob="go build"
alias gor="go run" 
alias goc="go clean -i"
alias gta="go test ./..."       # go test all
alias gia="go install ./..."    # go install all

# JS

# PHP

# netstat
alias port="netstat -tulpn | grep"

# docker
alias docki="docker inspect"                                                    # display the information about a container
alias docke='docker exec -t -i'                                                 # going inside a container
alias dockrm='docker rm -f $(docker ps -a -q)'                                     # delete every containers / images
alias dockDE='docker rm $(docker ps -a -q) && docker rmi $(docker images -q)'   # delete every containers / images
alias dockstats='docker stats $(docker ps -q)'                                  # stats on images
alias dockls='docker ps'                                                        # list docker containers
alias dockimg='docker images'                                                   # list images installed
alias dockprune='docker system prune -a'                                        # prune everything
alias dockceu='docker-compose run --rm -u $(id -u):$(id -g)'                    # run as the host user
alias dockce='docker-compose run --rm'
alias docker-compose-dev='docker-compose -f docker-compose-dev.yml' # run a different config file than the default one

# Folders
alias work="cd $HOME/workspace"
alias projc="cd $HOME/projects"
alias doc="cd $HOME/Documents"
alias dow="cd $HOME/Downloads"
alias dot="cd $HOME/.config"

# VPN
alias vpn-start="/usr/bin/openvpn3 session-start --config /home/roberto-araujo/vpn-files/profile-saml.ovpn"
alias vpn-stop="/usr/bin/openvpn3 session-manage --disconnect --config /home/roberto-araujo/vpn-files/profile-saml.ovpn"
alias vpn-log="/usr/bin/openvpn3 log --config /home/roberto-araujo/vpn-files/profile-saml.ovpn"
alias vpn-stats="/usr/bin/openvpn3 session-stats --config /home/roberto-araujo/vpn-files/profile-saml.ovpn" 
alias vpn-ps="ps auxfwww | grep openvpn"
alias vpn-kill="pgrep openvpn | xargs sudo kill -9"

# Sec
function genk() {
  local pkey=~/.ssh/id_ed25519
  local keys=~/.ssh/keys

  if [[ -f "$pkey" ]]; then
    if [[ ! -d "$keys" ]]; then
      mkdir $keys
    fi
    
    cd ~/.ssh

    for key in id_ed25519*; do
      echo "$key"
      mv "$key" "$keys/${key}_$1"
    done

  fi

  ssh-keygen -o -a 100 -t ed25519 -f ~/.ssh/id_ed25519 -C "$1"
}

