vim.o.autoindent = true
vim.o.backspace = "indent,eol,start"
-- vim.o.background = false
vim.o.clipboard = "unnamedplus"
vim.o.encoding = "UTF-8"
vim.o.expandtab = true
vim.o.exrc = true
-- vim.o.foldmethod="indent"
-- vim.o.guicursor = true
vim.o.hidden = true
vim.o.inccommand = "split"
vim.o.incsearch = true
vim.g.indentLine_char = "┊"
vim.o.ma = true
vim.g.mapleader = " "
vim.o.mouse = "a"
vim.g.nobackup = true
vim.g.nocompatible = true
vim.g.noerrorbells = true
-- vim.o.nofoldenable = true
vim.g.nohlsearch = true
vim.g.noswapfile = true
vim.o.nu = true
vim.o.number = true
vim.o.relativenumber = true
vim.o.scrolloff = 8
vim.o.shiftwidth = 2
vim.o.signcolumn = "yes"
vim.o.softtabstop = 2
vim.o.smartindent = true
-- vim.o.tabline = true
vim.o.tabstop = 2
vim.g.autoformat = false
